trigger:
- main

pool:
  name: mylinuxagent   # your self-hosted agent

variables:
  buildConfiguration: 'Release'
  publishDir: '$(Build.ArtifactStagingDirectory)/publish'
  swaggerJson: '$(Build.ArtifactStagingDirectory)/publish/swagger.json'
  apiVersion: 'v1'
  apimResourceGroup: 'Azure-poc'
  apimServiceName: 'IdentityServiceapi'
  apimApiId: 'IdentityService'
  apimApiPath: 'identityservice'
  apimAppServiceUrl: 'https://identityservice-gudxdgdna2fnbqa9.centralindia-01.azurewebsites.net'

steps:
# Build & publish the web app
- task: DotNetCoreCLI@2
  displayName: 'dotnet publish IdentityService'
  inputs:
    command: 'publish'
    projects: 'src/IdentityService/IdentityService.csproj'   # adjust path to your .csproj
    arguments: '--configuration $(buildConfiguration) --output $(publishDir)'

# Install Swashbuckle CLI (version compatible with .NET 8)
- script: dotnet tool install --global Swashbuckle.AspNetCore.Cli --version 6.5.0
  displayName: 'Install Swashbuckle CLI'

# Generate OpenAPI spec from published DLL
- script: swagger tofile --output "$(swaggerJson)" "$(publishDir)/IdentityService.dll" "$(apiVersion)"
  displayName: 'Generate Swagger spec'

# Publish artifact (optional)
- task: PublishBuildArtifacts@1
  displayName: 'Publish build artifacts'
  inputs:
    PathtoPublish: '$(publishDir)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

# Deploy to Azure Web App (Linux)
- task: AzureRmWebAppDeployment@5
  displayName: 'Deploy to Azure WebApp'
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure subscription 1(2c87b94c-e748-4605-a6fc-dd3ba336fc50)'
    appType: 'webAppLinux'   # change to 'webApp' if your App Service runs on Windows
    WebAppName: 'IdentityService'
    packageForLinux: '$(publishDir)'
    DeploymentTypeLinux: 'oneDeploy'

# Import or update API in Azure API Management
- task: AzureCLI@2
  displayName: 'Import API into APIM'
  inputs:
    azureSubscription: 'Azure subscription 1(2c87b94c-e748-4605-a6fc-dd3ba336fc50)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo "Importing API into APIM..."
      az apim api import \
        --resource-group $(apimResourceGroup) \
        --service-name $(apimServiceName) \
        --api-id $(apimApiId) \
        --path $(apimApiPath) \
        --specification-path $(swaggerJson) \
        --specification-format OpenApi \
        --service-url $(apimAppServiceUrl) \
        --subscription-required false
