trigger:
- main

pool:
  name: mylinuxagent

variables:
  buildConfiguration: 'Release'

steps:
# Build & publish in one step
- task: DotNetCoreCLI@2
  displayName: 'dotnet publish'
  inputs:
    command: 'publish'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/publish'

# Publish artifact (optional for releases or downloads)
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/publish'
    ArtifactName: 'drop'
    publishLocation: 'Container'

# Deploy directly from folder (no zip required)
- task: AzureRmWebAppDeployment@5
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure subscription 1(2c87b94c-e748-4605-a6fc-dd3ba336fc50)'
    appType: 'webAppLinux'
    WebAppName: 'IdentityService'
    deployToSlotOrASE: true
    ResourceGroupName: 'Azure-poc'
    SlotName: 'production'
    packageForLinux: '$(Build.ArtifactStagingDirectory)/publish'
    DeploymentTypeLinux: 'oneDeploy'
